/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.biblioteca_pi.telas;

import com.mycompany.biblioteca_pi.model.implementacao.ConexaoJPA;
import com.mycompany.biblioteca_pi.model.implementacao.ConsultasJPA;
import com.mycompany.biblioteca_pi.model.implementacao.LivrosJPA;
import jakarta.persistence.EntityManager;
import jakarta.persistence.EntityManagerFactory;
import java.sql.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author schuab
 */
public class Biblioteca extends javax.swing.JFrame {

    private EntityManager entityManager;
    EntityManagerFactory entityManagerFactory = ConexaoJPA.getEntityManagerFactory();
    LivrosJPA livroJPA = new LivrosJPA(entityManager);
    String nome;

    public Biblioteca(String nome) {
        this.nome = nome;
        initComponents();
        entityManager = entityManagerFactory.createEntityManager();
        livroJPA = new LivrosJPA(entityManager);
        carregarDadosNaTabela();
        centralizarConteudoTabela();
        botoes();
    }

    public Biblioteca() {
    }

    private void carregarDadosNaTabela() {
        ConsultasJPA consultasJPA = new ConsultasJPA();

        List<Object[]> resultadosLivros = consultasJPA.consultarInformacoesLivro();
        DefaultTableModel model = (DefaultTableModel) tblLivros.getModel();

        model.setRowCount(0);

        for (Object[] row : resultadosLivros) {
            // Mapear os valores corretamente para as colunas da tabela
            String livro = (String) row[0];
            String autor = (String) row[1];
            String genero = (String) row[2];
            Date data_lancamento = (Date) row[3];

            // Adicionar a linha na tabela
            model.addRow(new Object[]{livro, autor, genero, data_lancamento});
        }
    }

    //método para deixar centralizado os dados na tabela
    private void centralizarConteudoTabela() {

        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);

        for (int i = 0; i < tblLivros.getColumnCount(); i++) {
            tblLivros.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }
    }

    private void atualizarTabela(List<Object[]> resultados) {
        DefaultTableModel model = (DefaultTableModel) tblLivros.getModel();
        model.setRowCount(0); // Limpar todas as linhas da tabela

        for (Object[] row : resultados) {
            model.addRow(row); // Adicionar cada linha de resultado à tabela
        }
    }

    public void botoes() {

        if (nome.equals("user")) {
            btnBuscar.setVisible(true);
            btnCadastrarCliente.setVisible(false);
            btnCadastrarLivro.setVisible(false);
            btnEmprestimo.setVisible(false);
            btnExcluir.setVisible(false);
            btnSair.setVisible(true);
        } else if (nome.equals("bibliotecaria")) {
            btnBuscar.setVisible(true);
            btnCadastrarCliente.setVisible(true);
            btnCadastrarLivro.setVisible(true);
            btnEmprestimo.setVisible(true);
            btnExcluir.setVisible(true);
            btnSair.setVisible(true);
        } else {
            btnBuscar.setVisible(false);
            btnCadastrarCliente.setVisible(false);
            btnCadastrarLivro.setVisible(false);
            btnEmprestimo.setVisible(false);
            btnExcluir.setVisible(false);
            btnSair.setVisible(true);
            txtBuscarLivro.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BarraMenu = new javax.swing.JPanel();
        txtBuscarLivro = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnCadastrarLivro = new javax.swing.JButton();
        btnCadastrarCliente = new javax.swing.JButton();
        BarraRodape = new javax.swing.JPanel();
        labelCelular = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        btnEmprestimo = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        labelEmail = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLivros = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BarraMenu.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/loupe.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Swis721 Hv BT", 0, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/booksMenu.png"))); // NOI18N
        jLabel1.setText("Biblioteca Virtual ");

        btnCadastrarLivro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/register.png"))); // NOI18N
        btnCadastrarLivro.setText("Novo Livro");
        btnCadastrarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarLivroActionPerformed(evt);
            }
        });

        btnCadastrarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cadastrar.png"))); // NOI18N
        btnCadastrarCliente.setText("Novo Cliente");
        btnCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BarraMenuLayout = new javax.swing.GroupLayout(BarraMenu);
        BarraMenu.setLayout(BarraMenuLayout);
        BarraMenuLayout.setHorizontalGroup(
            BarraMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BarraMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(txtBuscarLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCadastrarCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCadastrarLivro)
                .addContainerGap())
        );
        BarraMenuLayout.setVerticalGroup(
            BarraMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BarraMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(jLabel1)
                    .addComponent(btnCadastrarLivro)
                    .addComponent(btnCadastrarCliente))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        BarraRodape.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BarraRodape.setPreferredSize(new java.awt.Dimension(0, 40));

        labelCelular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/whatsapp.png"))); // NOI18N
        labelCelular.setText("(21) 98765-4321");
        labelCelular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelCelularMouseClicked(evt);
            }
        });

        jLabel2.setText("Contatos:");

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logout.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnEmprestimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bookRodape.png"))); // NOI18N
        btnEmprestimo.setText("Empréstimo");
        btnEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmprestimoActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lixeira.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        labelEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/message.png"))); // NOI18N
        labelEmail.setText("biblioteca@hotmail.com");
        labelEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelEmailMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BarraRodapeLayout = new javax.swing.GroupLayout(BarraRodape);
        BarraRodape.setLayout(BarraRodapeLayout);
        BarraRodapeLayout.setHorizontalGroup(
            BarraRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BarraRodapeLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelCelular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExcluir)
                .addGap(12, 12, 12)
                .addComponent(btnEmprestimo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSair)
                .addContainerGap())
        );
        BarraRodapeLayout.setVerticalGroup(
            BarraRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BarraRodapeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BarraRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(labelCelular)
                    .addComponent(labelEmail)
                    .addComponent(btnEmprestimo)
                    .addComponent(btnExcluir)
                    .addComponent(btnSair))
                .addContainerGap())
        );

        jScrollPane1.setBackground(new java.awt.Color(61, 122, 153));
        jScrollPane1.setBorder(null);

        tblLivros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Livro", "Autor", "Gênero", "Ano "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblLivros);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BarraMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BarraRodape, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BarraMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BarraRodape, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // Obter o texto inserido no campo de busca
        String termoBusca = txtBuscarLivro.getText().trim();

        // Verificar se o campo de busca está vazio
        if (termoBusca.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite um termo de busca.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Instanciar a classe ConsultasJPA
        ConsultasJPA consultasJPA = new ConsultasJPA();

        // Realizar a consulta com base no termo de busca
        List<Object[]> resultadosBusca = consultasJPA.consultarInformacoesLivro(termoBusca);

        // Atualizar a tabela com os resultados da busca
        atualizarTabela(resultadosBusca);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnCadastrarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarLivroActionPerformed
        new CadastroLivro(nome).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCadastrarLivroActionPerformed

    private void btnCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarClienteActionPerformed
        new CadastroCliente(nome).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCadastrarClienteActionPerformed

    private void labelCelularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCelularMouseClicked
        JOptionPane.showInputDialog(null, "Enviar menssagem com o seguinte texto:", "Enviar menssagem para **(21) 98765-4321**", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_labelCelularMouseClicked

    private void labelEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelEmailMouseClicked
        JOptionPane.showInputDialog(null, "Enviar E-mail com o seguinte conteúdo:", "Enviar E-mail para **biblioteca@hotmail.com**", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_labelEmailMouseClicked

    private void btnEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmprestimoActionPerformed
        new TelaEmprestimo(nome).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnEmprestimoActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // Verificar se foi selecionada alguma linha na tabela
        int selectedRow = tblLivros.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um livro para excluir.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Obter o ID do livro selecionado na tabela
        String nome_livro = (String) tblLivros.getValueAt(selectedRow, 0);

        // Confirmar se o usuário deseja realmente excluir o livro
        int confirmacao = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja excluir este livro?", "Confirmar exclusão", JOptionPane.YES_NO_OPTION);
        if (confirmacao == JOptionPane.YES_OPTION) {
            // Excluir o livro utilizando o método da classe LivrosJPA
            livroJPA.excluirLivro(nome_livro);

            // Recarregar os dados na tabela após a exclusão
            carregarDadosNaTabela();
            centralizarConteudoTabela();
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        new Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Biblioteca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarraMenu;
    private javax.swing.JPanel BarraRodape;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCadastrarCliente;
    private javax.swing.JButton btnCadastrarLivro;
    private javax.swing.JButton btnEmprestimo;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCelular;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JTable tblLivros;
    private javax.swing.JTextField txtBuscarLivro;
    // End of variables declaration//GEN-END:variables
}
