/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.biblioteca_pi.telas;

import com.mycompany.biblioteca_pi.model.implementacao.ConsultasJPA;
import com.mycompany.biblioteca_pi.model.implementacao.EmprestimoJPA;
import java.sql.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author schuab
 */
public class TelaEmprestimo extends javax.swing.JFrame {

    String usuario;

    public TelaEmprestimo(String nome) {
        this.usuario = nome;
        initComponents();
        preencherTabela();
        centralizarConteudoTabela();
    }

    TelaEmprestimo() {
    }

    private void preencherTabela() {
        ConsultasJPA consultasJPA = new ConsultasJPA();

        List<Object[]> resultadosLivros = consultasJPA.consultarInformacoesEmprestimo();
        DefaultTableModel model = (DefaultTableModel) tblEmprestimo.getModel();

        model.setRowCount(0);

        for (Object[] row : resultadosLivros) {
            // Mapear os valores corretamente para as colunas da tabela
            String livro = (String) row[0];
            String cliente = (String) row[1];
            Date data = (Date) row[2];
            String emprestado = (String) row[3];

            // Adicionar a linha na tabela
            model.addRow(new Object[]{livro, cliente, data, emprestado});
        }
    }

    //método para deixar centralizado os dados na tabela
    private void centralizarConteudoTabela() {

        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);

        for (int i = 0; i < tblEmprestimo.getColumnCount(); i++) {
            tblEmprestimo.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BarraMenu = new javax.swing.JPanel();
        txtBuscarEmprestimo = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        logoBiblioteca = new javax.swing.JLabel();
        btnEmprestarLivro = new javax.swing.JButton();
        btnDevolver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmprestimo = new javax.swing.JTable();
        BarraRodape = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        labelCelular = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BarraMenu.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/loupe.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        logoBiblioteca.setFont(new java.awt.Font("Swis721 Hv BT", 0, 12)); // NOI18N
        logoBiblioteca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/booksMenu.png"))); // NOI18N
        logoBiblioteca.setText("Biblioteca Virtual ");
        logoBiblioteca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoBibliotecaMouseClicked(evt);
            }
        });

        btnEmprestarLivro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bookRodape.png"))); // NOI18N
        btnEmprestarLivro.setText("Emprestar Livro");
        btnEmprestarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmprestarLivroActionPerformed(evt);
            }
        });

        btnDevolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/guardar.png"))); // NOI18N
        btnDevolver.setText("Devolver Livro");
        btnDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BarraMenuLayout = new javax.swing.GroupLayout(BarraMenu);
        BarraMenu.setLayout(BarraMenuLayout);
        BarraMenuLayout.setHorizontalGroup(
            BarraMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BarraMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoBiblioteca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(txtBuscarEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEmprestarLivro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDevolver)
                .addContainerGap())
        );
        BarraMenuLayout.setVerticalGroup(
            BarraMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BarraMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(logoBiblioteca)
                    .addComponent(btnEmprestarLivro)
                    .addComponent(btnDevolver))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        tblEmprestimo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Livro", "Cliente", "Data", "Emprestado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblEmprestimo);

        BarraRodape.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BarraRodape.setPreferredSize(new java.awt.Dimension(0, 40));

        jLabel2.setText("Contatos:");

        labelCelular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/whatsapp.png"))); // NOI18N
        labelCelular.setText("(21) 98765-4321");
        labelCelular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelCelularMouseClicked(evt);
            }
        });

        labelEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/message.png"))); // NOI18N
        labelEmail.setText("biblioteca@hotmail.com");
        labelEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelEmailMouseClicked(evt);
            }
        });

        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/back.png"))); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lixeira.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BarraRodapeLayout = new javax.swing.GroupLayout(BarraRodape);
        BarraRodape.setLayout(BarraRodapeLayout);
        BarraRodapeLayout.setHorizontalGroup(
            BarraRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraRodapeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelCelular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVoltar)
                .addContainerGap())
        );
        BarraRodapeLayout.setVerticalGroup(
            BarraRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraRodapeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BarraRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(labelCelular)
                    .addComponent(labelEmail)
                    .addComponent(btnVoltar)
                    .addComponent(btnExcluir))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BarraMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BarraRodape, javax.swing.GroupLayout.DEFAULT_SIZE, 801, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BarraMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BarraRodape, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // Obtém o termo de busca digitado pelo usuário
        String termoBusca = txtBuscarEmprestimo.getText().trim();

        // Verifica se o campo de busca não está vazio
        if (!termoBusca.isEmpty()) {
            // Realiza a consulta com base no termo de busca
            ConsultasJPA consultasJPA = new ConsultasJPA();
            List<Object[]> resultadosBusca = consultasJPA.consultarInformacoesEmprestimo(termoBusca);

            // Atualiza a tabela com os resultados da busca
            DefaultTableModel model = (DefaultTableModel) tblEmprestimo.getModel();
            model.setRowCount(0); // Limpa as linhas existentes na tabela

            for (Object[] row : resultadosBusca) {
                model.addRow(row); // Adiciona cada linha de resultado à tabela
            }
        } else {
            // Se o campo de busca estiver vazio, exibe uma mensagem de erro
            JOptionPane.showMessageDialog(this, "Por favor, digite um termo de busca.", "Campo de busca vazio", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void logoBibliotecaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoBibliotecaMouseClicked
        new Biblioteca(usuario).setVisible(true);
        dispose();
    }//GEN-LAST:event_logoBibliotecaMouseClicked

    private void btnEmprestarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmprestarLivroActionPerformed
        new EmprestarLivro(usuario).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnEmprestarLivroActionPerformed

    private void btnDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolverActionPerformed
        // Verifica se alguma linha da tabela está selecionada
        int linhaSelecionada = tblEmprestimo.getSelectedRow();
        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(this, "Por favor, selecione um empréstimo na tabela.", "Nenhum empréstimo selecionado", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Obtém os detalhes do empréstimo selecionado
        String nomeLivro = (String) tblEmprestimo.getValueAt(linhaSelecionada, 0);
        String nomeCliente = (String) tblEmprestimo.getValueAt(linhaSelecionada, 1);
        Date dataEmprestimo = (Date) tblEmprestimo.getValueAt(linhaSelecionada, 2);
        String emprestado = (String) tblEmprestimo.getValueAt(linhaSelecionada, 3);

        EmprestimoJPA emprestimoJPA = new EmprestimoJPA();
        Integer idEmprestimo = emprestimoJPA.buscarIdEmprestimo(nomeLivro, nomeCliente, dataEmprestimo, emprestado);

        // Verifica se o ID do empréstimo foi encontrado
        if (idEmprestimo == null) {
            JOptionPane.showMessageDialog(this, "Não foi possível encontrar o ID do empréstimo.", "ID não encontrado", JOptionPane.ERROR_MESSAGE);
            return;
        }

        emprestimoJPA.devolverLivro(idEmprestimo);

        preencherTabela();
        centralizarConteudoTabela();

    }//GEN-LAST:event_btnDevolverActionPerformed

    private void labelCelularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCelularMouseClicked
        JOptionPane.showInputDialog(null, "Enviar menssagem com o seguinte texto:", "Enviar menssagem para **(21) 98765-4321**", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_labelCelularMouseClicked

    private void labelEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelEmailMouseClicked
        JOptionPane.showInputDialog(null, "Enviar E-mail com o seguinte conteúdo:", "Enviar E-mail para **biblioteca@hotmail.com**", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_labelEmailMouseClicked

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        new Biblioteca(usuario).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // Verifica se alguma linha da tabela está selecionada
        int linhaSelecionada = tblEmprestimo.getSelectedRow();
        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(this, "Por favor, selecione um empréstimo na tabela.", "Nenhum empréstimo selecionado", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Obtém os detalhes do empréstimo selecionado
        String nomeLivro = (String) tblEmprestimo.getValueAt(linhaSelecionada, 0);
        String nomeCliente = (String) tblEmprestimo.getValueAt(linhaSelecionada, 1);
        Date dataEmprestimo = (Date) tblEmprestimo.getValueAt(linhaSelecionada, 2);
        String emprestado = (String) tblEmprestimo.getValueAt(linhaSelecionada, 3);

        EmprestimoJPA emprestimoJPA = new EmprestimoJPA();
        Integer idEmprestimo = emprestimoJPA.buscarIdEmprestimo(nomeLivro, nomeCliente, dataEmprestimo, emprestado);

        // Verifica se o ID do empréstimo foi encontrado
        if (idEmprestimo == null) {
            JOptionPane.showMessageDialog(this, "Não foi possível encontrar o ID do empréstimo.", "ID não encontrado", JOptionPane.ERROR_MESSAGE);
            return;
        }

        emprestimoJPA.excluirEmprestimo(idEmprestimo);

        preencherTabela();
        centralizarConteudoTabela();
    }//GEN-LAST:event_btnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEmprestimo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarraMenu;
    private javax.swing.JPanel BarraRodape;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnDevolver;
    private javax.swing.JButton btnEmprestarLivro;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCelular;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel logoBiblioteca;
    private javax.swing.JTable tblEmprestimo;
    private javax.swing.JTextField txtBuscarEmprestimo;
    // End of variables declaration//GEN-END:variables
}
